### PR TITLE
Disable thumb fallback

### PR DESCRIPTION
**Pull request by benjaminpick**
I am using the plugin to implement GDPR. Thus, it is important that all communication of the client with the YouTube servers happen with the user's consent.
In error conditions, lyteCache.php currently falls back to redirecting to the YouTube thumbnail directly. While this is user-friendly, it had the consequence that I didn't discover this behaviour until some days ago, although the error was introduced some months ago. The error can also be a server configuration error (e.g. curl not installed) or other, so the plugin cannot make 100% sure it can avoid the error conditions.

This pull request is introducing a filter. When this code is added e.g. in the template:

```php
add_filter( 'lyte_filter_disable_thumb_fallback', '__return_true' );
```

it will disable this fallback mechanicsm and show an empty grey image instead.

Also, I have added 2 exits after the HTTP headers as this is being considered best practise to avoid continuing execution ...

### CODE REVIEW

**Comment by futtta** [comment]
Nice idea Benjamin! Could you make the image smaller (can it be just a grey
pixel?) and can you store it as a base64-encoded string in lyteCache.php?
That way we have one less file, and one less file to read from the
filesystem, you just send the base64-decoded string?

**Comment by benjaminpick** [comment]
Hm ... as 1x1 Pixel, the JPG file is not much smaller (338 Bytes), GIF
(35 bytes) or PNG (69 bytes) seem to be better options then.

But a 1x1 image might impact the browser perfomance?

https://stackoverflow.com/a/23893788 is suggesting using a 10x10 image

For us, that would be GIF (41 bytes) or PNG (78 bytes) - seems like a
good compromise? AFAIK, gif is supported by all browsers, so I just have
to make the content-type configurable.

**Comment by futtta** [comment]
then go for base64 encode 10X10 gif in that case? but what do you mean
"make the content-type configurable"?

**Comment by benjaminpick** [comment]
I have updated the pull request accordingly ...

**Pull request merged**
